# Array Mathematics



Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.

In [6]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print(a+b)
print(numpy.add(a, b))

print(a-b)
print(numpy.subtract(a, b))

print(a*b)
print(numpy.multiply(a, b))

print(a/b)
print(numpy.divide(a, b))

print(a%b)
print(numpy.mod(a, b))

print(a**b)
print(numpy.power(a, b))

[  6.   8.  10.  12.]
[  6.   8.  10.  12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[  5.  12.  21.  32.]
[  5.  12.  21.  32.]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


Task

You are given two integer arrays, A and B of dimensions NXM.
Your task is to perform the following operations:
    
 - Add ( A+B )
 - Subtract ( A-B )
 - Multiply ( A*B )
 - Integer Division ( A/B )
 - Mod ( A%B )
 - Power ( A**B )

In [18]:
import numpy as np
n,m = map(int,input().split())

a=np.zeros((n,m),int)
b=np.zeros((n,m),int)
for i in range(n):
    a[i]=np.array(input().split(),int)
for i in range(n):
    b[i]=np.array(input().split(),int)  

print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [19]:
# OR

import numpy as np
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

2 4
1 2 3 4
1 2 3 4
5 6 7 7
5 6 7 7
[[ 6  8 10 11]
 [ 6  8 10 11]]
[[-4 -4 -4 -3]
 [-4 -4 -4 -3]]
[[ 5 12 21 28]
 [ 5 12 21 28]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]]
[[    1    64  2187 16384]
 [    1    64  2187 16384]]
