# Eye and Identity



identity

The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as 1 and the rest as 0. The default type of elements is float.

In [1]:
import numpy

print(numpy.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


eye

The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

In [2]:
import numpy

print(numpy.eye(8, 7, k = 1))

print(numpy.eye(8, 7, k = -2))

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


Task

Your task is to print an array of size NXM with its main diagonal elements as 1's and s's everywhere else.

In [9]:
import numpy

print(numpy.eye(*map(int, input().split())))

3 3
3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
