# Floor, Ceil and Rint

floor

The tool floor returns the floor of the input element-wise.

The floor of x is the largest integer i where i <= x.

In [1]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(numpy.floor(my_array))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


ceil

The tool ceil returns the ceiling of the input element-wise.

The ceiling of x is the smallest integer i where i >= x.

In [3]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(numpy.ceil(my_array))  

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


rint

The rint tool rounds to the nearest integer of input element-wise.

NOTE: 0.5 is rounded to next closest integer number

In [5]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(numpy.rint(my_array)) 

[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


Task

You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of .

In [6]:
import numpy

A = numpy.array(input().split(), dtype = float)

print(numpy.floor(A), numpy.ceil(A), numpy.rint(A), sep = "\n")

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]
