# Shape and Reshape



shape

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

In [3]:
import numpy

my__1D_array = numpy.array([1,2,3,4,5])
print(my__1D_array)

my__2D_array = numpy.array([[1,2], [3,4], [6,5]])
print(my__2D_array)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [6 5]]


In [5]:
import numpy

change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print(change_array)      


[[1 2]
 [3 4]
 [5 6]]


reshape

The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

In [7]:
import numpy

my_array = numpy.array([1,2,3,4,5,6])
print(numpy.reshape(my_array, (3,2)))

[[1 2]
 [3 4]
 [5 6]]


Task

You are given a space separated list of nine integers. Your task is to convert this list into a 3 X 3 NumPy array.

In [12]:
import numpy

print(numpy.reshape(numpy.array(input().split(), int), (3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
