# Transpose and Flatten

Transpose

We can generate the transposition of an array using the tool numpy.transpose.
It will not affect the original array, but it will create a new array.

In [4]:
import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(numpy.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


Flatten

The tool flatten creates a copy of the input array flattened to one dimension.

In [3]:
import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(my_array.flatten())

[1 2 3 4 5 6]


Task

You are given a NXM integer array matrix with space separated elements (N = rows and M = columns).

Your task is to print the transpose and flatten results.



In [8]:
import numpy


n, m = map(int, input().split())
l = list()
for _ in range(n):
    l.append(list(map(int, input().split())))

arr = numpy.array(l)

print(numpy.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [9]:
# OR

n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print(array.transpose())
print(array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]
