# Zeros and Ones

zeros

The zeros tool returns a new array with a given shape and type filled with 0's.

In [2]:
import numpy

print(numpy.zeros((1,2)))

print(numpy.zeros((1,2), numpy.int))

[[0. 0.]]
[[0 0]]


ones

The ones tool returns a new array with a given shape and type filled with 1's

In [4]:
import numpy

print(numpy.ones((1,2)))

print(numpy.ones((1,2), numpy.int))

[[1. 1.]]
[[1 1]]


Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [14]:
import numpy

dim = tuple(map(int, input().split()))

print(numpy.zeros(dim, numpy.int))
print(numpy.ones(dim, numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
